export interface CandidatesResponse<T> {
  records: T[];
  totalRecords?: number;
}

export interface CandidateDTO {
  ConsIntID: string;
  ConsultantID: string;
  Title: string;
  FirstName: string;
  MiddleName: string;
  LastName: string;
  Suffix: string;
  NickName: string;
  DisplayName: string;
  Available: boolean;
  CompanyName: string;
  AvailabilityDate: string | null;
  AvailabilityNotice: string;
  JobTitle: string;
  PrimarySkills: string;
  SecondarySkills: string;
  OtherSkills: string;
  TotalExp: {
    role: string;
    company: string;
    location: string;
    duration: string;
    description: string[];
  }[];
  USExp: string;
  CommSkills: string;
  Rate: string;
  Relocation: string;
  ResumeDir: string;
  ResumeFile: string;
  ModifiedResumeDir: string;
  ModifiedResumeFile: string;
  ResumeWebPath: string;
  Summary: string;
  AdditionalInfo: string;
  ReferredBy: string;
  XMLResume: string;
  SSN: string;
  VisaStatus: string;
  VisaExpiryDate: string | null;
  Address1: string;
  Address2: string;
  Address3: string;
  City: string;
  State: string;
  ZipCode: string;
  Country: string;
  HomePhone: string;
  WorkPhone: string;
  MobilePhone: string;
  Fax: string;
  EMail1: string;
  EMail2: string;
  Salary: number;
  SalaryReviewDate: string | null;
  BonusAmount: number;
  BonusAmountDate: string | null;
  DOE: string | null;
  DOT: string | null;
  DOB: string | null;
  DOM: string | null;
  SpouseName: string;
  EmergencyContactName: string;
  EmergencyPhone: string;
  Notes: string;
  Archived: boolean;
  SendInHotList: boolean;
  Employee: boolean;
  JobType: string;
  Categories: string;
  Groups: string;
  Owners: string;
  EmployeeNumber: string;
  OnHold: boolean;
  OnHoldTill: string | null;
  VacationDays: number;
  SickDays: number;
  TableHolidays: boolean;
  FloatHolidays: number;
  LinkToIntID: string;
  UserIDs: string;
  Private: boolean;
  CreateDate: string;
  EditDate: string;
  MergeDate: string | null;
  UserField1: string;
  UserField2: string;
  UserField3: string;
  UserField4: string;
  UserField5: string;
  UserField6: string;
  UserField7: number;
  UserField8: number;
  UserField9: string;
  UserField10: string;
  Field1: string;
  Field2: string;
  Field3: string;
  uuTimesheet: boolean;
  uuResumeText: string;
  uuCandidateStatus: string;
  OwnershipCheck: number;
  OwnershipDate: string | null;
  uuDisclaimer: boolean;
  uuAuthorized: boolean;
  uuBackground: boolean;
  uuOldNotes: string;
  uuTargetJobTitle: string;
  uuHighestEducation: string;
  uuAuthorizedToWorkIn: string;
  JobBoardIDs: string;
  uuSourceWebSites: string;
  uuCoUserIDs: string;
  uuActiveLicenses: string;
  uuLanguages: string;
  uuSpouseOccupation: string;
  uuHobbies: string;
  PostedJobURLs: string;
  ExternalJobIDs: string;
  PostedAPIs: string;
  OptOut: boolean;
  uuLinkedInURL: string;
  uuGooglePlusURL: string;
  uuFaceBookURL: string;
  uuTwitterURL: string;
  BounceCount: number;
  LastBounceDate: string | null;
  LastActivityDate: string | null;
  LastActivityType: string;
  CreatedBy: string;
  ResumeDate: string;
  Rating: number;
  Status: string;
  BillRate: number;
  PayRate: number;
  Burden: number;
  Description: string;
  Certifications: string;
  TravelPreference: string;
  PendingTimeSheets: boolean;
  AdpUserID: string;
  AdpPwd: string;
  InsType: string;
  InsStartDt: string | null;
  InsEndDt: string | null;
  InsAmt: number;
  InsTermDt: string | null;
  InsInfo: string;
  TimeShtRecDt: string | null;
  ExpShtRecDt: string | null;
  PaymentRecDt: string | null;
  ExpRecDt: string | null;
  CoveragePlan: string;
  VisaStartDate: string | null;
  VisaEndDate: string | null;
  WorkAddress1: string;
  WorkCity: string;
  WorkState: string;
  WorkZipCode: string;
  CheckBox1: boolean;
  CheckBox2: boolean;
  CheckBox3: boolean;
  CheckBox4: boolean;
  CheckBox5: boolean;
  DateField1: string | null;
  DateField2: string | null;
  DateField3: string | null;
  DateField4: string | null;
  DateField5: string | null;
  Summary1: string;
  Summary2: string;
  Summary3: string;
  DesiredSalary: number;
  Industry: string;
  Seniority: string;
  Languages: string;
  JobFunction: string;
  IsContact: boolean;
  MirrorIntID: string;
  Compensation: string;
  uuMethodOfContact: string;
  uuNotary: boolean;
  TargetJobTitle: string;
  IndeedURL: string;
  uuIndeedURL: string;
  OpenedDate: string;
  OpenedBy: string;
  uuEditedBy: string;
  SMSOptOut: boolean;
  SkillMatrix: string;
  ProfileImageURL: string;
  ProfileImage: string;
  ImageURL: string;
  ExpectedPay: string;
  EmVerifiedStatus: string;
  EmVerifiedDate: string | null;
  HireezID: string;
  HubSpotID: string;
  uuPushToHubSpot: boolean;
  IndeedApplyID: string;
  OPT: boolean;
  LINJoinDate: string | null;
  PKQNIntIDs: string;
  Fake__ItemCaption: string;
}

export interface SkillMatrixItem {
  name: string;
  years: string;
  level: number;
  keywords?: string[];
}

export interface Candidate extends Omit<
  CandidateDTO,
  'PrimarySkills' | 'SkillMatrix' | 'SecondarySkills'
> {
  FullName: string;
  PrimarySkills: string[];
  SkillMatrix: SkillMatrixItem[];
  AvatarLabel: string;
  SecondarySkills: string[];
}

export type StageType = 'Received' | 'Potential' | 'Interview' | 'Offer' | 'Placed';

export interface PipelineStageDTO {
  ConsIntID: string;
  Stage: StageType;
  ContactIntID: string;
  Contact: string;
  Company: string;
  ReqIntID: string;
  Requirement: string;
  JobTitle: string;
  MLinkIntID: string;
  Subject: string;
  DateAndTime: string;
  UserID: string;
  ClosedDate: string;
  Archived: boolean;
}

export interface PipelineStage extends Omit<PipelineStageDTO, 'DateAndTime' | 'ClosedDate'> {
  DateAndTime: Date;
  ClosedDate: Date;
}

export interface PipelineJob {
  job: string;
  company: string;
  jobTitle: string;
  contact: string;
  stage: StageType;
  lastUpdated: Date;
  stages: PipelineStage[];
}
